variables:
  release_notes_wiki_path: NRG-Rest-Services/release-notes.md  # <app-name>/release-notes.md

resources:
  repositories:
    - repository: templates
      type: git
      name: Digital-IT-Projects/azure-build-templates

pool:
  #vmImage: 'ubuntu-16.04'
  name: '$(param.agent.pool.name)'  

trigger:
  branches:
    include:
    - develop
    - master
    - features/*
  paths:
    exclude:
    - README.md

stages:
  - stage:
    displayName: Checkout
    jobs:
      - job:
        displayName: Checkout App

  - stage:
    displayName: Generate release notes N trigger Jenkins
    jobs:
      - template: create_release_notes_n_autotag.yml@templates

      - job:
        displayName: Trigger Jenkins
        steps:
          - task: JenkinsQueueJob@2
            displayName: 'Queue Jenkins job: Services/nrg-rest-services'
            inputs:
              serverEndpoint: 'Prod Jenkins'
              jobName: 'Services/nrg-rest-services'
              isMultibranchJob: true
              multibranchPipelineBranch: '$(Build.SourceBranch)'