
pool:
  name: '$(param.agent.pool.name)'  

trigger:
  branches:
    include:
    - develop
    - master
    - features/*
  paths:
    exclude:
    - README.md

stages:
  - stage:
    displayName: Build and Scan
    jobs:
      - job: Build
        displayName: Build
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx512m'
            goals: 'clean dependency:copy-dependencies package -Pserver-profile -U -T 1C'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: true
            sonarQubeRunAnalysis: false
            sqMavenPluginVersionChoice: 'latest'
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/dependency/*.jar'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: WhiteSource Bolt@20
          displayName: 'WhiteSource Scan for $(Build.Repository.Name)'
          inputs:
            cwd: '$(Build.ArtifactStagingDirectory)'