
pool:
  name: '$(param.agent.pool.name)'  

trigger:
  branches:
    include:
    - develop
    - master
    - features/*
  paths:
    exclude:
    - README.md

stages:
  - stage:
    displayName: Build and Scan
    jobs:
      - job: Build
        displayName: Build
        steps:
        - task: SonarQubePrepare@4
          inputs:
            SonarQube: 'PROD-SONAR'
            scannerMode: 'CLI'
            configMode: 'file'
            extraProperties: |
              # Additional properties that will be passed to the scanner, 
              # Put one key=value per line, example:
              # sonar.exclusions=**/*.bin
              sonar.pullrequest.vsts.instanceUrl=$(azureDevOpsOrganizationURL)
              sonar.pullrequest.vsts.project=$(System.TeamProject)
              sonar.pullrequest.vsts.repository=$(Build.Repository.Name)

        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx512m'
            goals: 'clean dependency:copy-dependencies package'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: true
            sonarQubeRunAnalysis: false
            sqMavenPluginVersionChoice: 'latest'
            
        - task: SonarQubeAnalyze@4
          displayName: 'Run Sonar Analysis'

        # - task: CopyFiles@2
        #   displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        #   inputs:
        #     SourceFolder: '$(System.DefaultWorkingDirectory)'
        #     Contents: '**/dependency/*.jar'
        #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
        # - task: WhiteSource Bolt@20
        #   displayName: 'WhiteSource Scan'
        #   inputs:
        #     cwd: '$(Build.ArtifactStagingDirectory)'