# This pipeline triggers the Jenkins pipeline and runs only for the 'develop' branch.
resources:
  repositories:
    - repository: templates
      type: git
      name: Digital-IT-Projects/azure-build-templates

variables:
  jenkinsJobName: 'Services/nrg-rest-services/'
  agentPoolName: $(param.agent.pool.name)
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isDeployBranch: $[contains(variables['Build.SourceBranch'], 'refs/heads/develop')]

pool:
  name: '$(param.agent.pool.name)'  

trigger:
  branches:
    include:
    - develop

  paths:
    exclude:
    - README.md
    - azure-pipelines-trigger-jenkins.yml
    - azure-pipelines.yml

stages:
  - template: hybrid_pipeline/include-jenkins-pipeline-trigger.yml@templates
    parameters:
      agent_pool_name: $(agentPoolName)
      jenkins_job_name: $(jenkinsJobName)