package com.multibrand.util;

import java.util.HashMap;
import java.util.Map;


public enum EmailTemplateEnum {
	
	 CIRRO_AUTO_PAY_UPDATE_EXTERNAL_ID_EN("CE.AUTO.PAY.UPDATE.EN_US"),
	 CIRRO_AVG_BILLING_CONF_EXTERNAL_ID_EN("CE.AVG.BILLING.CONF.EN_US"),
	 GME_PASSWORD_CHANGE_EN_US("GME.PASSWORD.CHANGE.EN_US"),
	 GME_PASSWORD_CHANGE_ES_US("GME.PASSWORD.CHANGE.ES_US"),
	 GME_USERNAME_EN_US("GME.USERNAME.EN_US"),
	 GME_USERNAME_ES_US("GME.USERNAME.ES_US"),
	 CIRRO_EMAIL_CHANGE_EXTERNAL_ID_EN("CE.EMAIL.UPDATE.EN_US"),
	 CIRRO_PAYMENT_OPTIONS_UPDATE_EN("CE.PAYMENT.OPTIONS.UPDATE.EN_US"),
	 CIRRO_BILLING_OPTION_CHANGE_EN("CE.BILLING.OPTION.CHANGE.EN_US"),
	 CIRRO_ADD_BANK_CONF_EXTERNAL_ID("CE.ADD.BANK.CONF.EN_US"),
	 CIRRO_PASSWORD_CHANGE_EXTERNAL_ID("CE.PASSWORD.CHANGE.EN_US"),
	 CIRRO_NEW_SERVICE_ADDRESS_ADD_EXTERNAL_ID("CE.ADD.NEW.SERVICE.ADDED.EN_US"),
	 CIRRO_CREDIT_DEBIT_UPDATE_EN("CE.ADD.CREDIT.DEBIT.UPDATE.EN_US"),
	 GME_AUTO_PAY_ENROLL_CONFIRM_BANK_EN_US("GME.AUTO.PAY.ENROLL.CONFIRM.BANK.EN_US"),
	 GME_AUTO_PAY_ENROLL_CONFIRM_BANK_ES_US("GME.AUTO.PAY.ENROLL.CONFIRM.BANK.ES_US"),
	 GME_AUTO_PAY_DEENROLL_CONFIRM_EN_US("GME.AUTO.PAY.DEENROLL.CONFIRM.EN_US"),
	 GME_AUTO_PAY_DEENROLL_CONFIRM_ES_US("GME.AUTO.PAY.DEENROLL.CONFIRM.ES_US"),
	 GME_BILL_PAY_CONFIRM_CC_EN_US("GME.BILL.PAY.CONFIRM.CC.EN_US"),
	 GME_BILL_PAY_CONFIRM_CC_ES_US("GME.BILL.PAY.CONFIRM.CC.ES_US"),
	 GME_AUTO_PAY_ENROLL_CONFIRM_CC_EN_US("GME.AUTO.PAY.ENROLL.CONFIRM.CC.EN_US"),
	 GME_AUTO_PAY_ENROLL_CONFIRM_CC_ES_US("GME.AUTO.PAY.ENROLL.CONFIRM.CC.ES_US"),
	 GME_EBILL_CONFR_ENROLL_FOLLOWUP_CONFIRM_EN_US("GME.EBILL.CONFR.ENROLL.FOLLOWUP.CONFIRM.EN_US"),
	 GME_EBILL_CONFR_ENROLL_FOLLOWUP_CONFIRM_ES_US("GME.EBILL.CONFR.ENROLL.FOLLOWUP.CONFIRM.ES_US"),
	 GME_OE_DIGITAL_SIGNATURE_CONFR_EN_US("GME.OE.DIGITAL.SIGNATURE.CONFR.EN_US"),
	 GME_OE_DIGITAL_SIGNATURE_CONFR_ES_US("GME.OE.DIGITAL.SIGNATURE.CONFR.ES_US"),
	 GME_SUBMIT_AMB_CONFIRM_EN_US("GME.SUBMIT.AMB.CONFIRM.EN_US"),
	 GME_SUBMIT_AMB_CONFIRM_ES_US("GME.SUBMIT.AMB.CONFIRM.ES_US"),
	 GME_BILL_PAY_CONFIRM_BANK_EN_US("GME_BILL_PAY_CONFIRM_BANK.EN_US"),
	 GME_BILL_PAY_CONFIRM_BANK_ES_US("GME_BILL_PAY_CONFIRM_BANK.ES_US"),
	 GME_SUBMIT_RETRO_AMB_CONFIRM_EN_US("GME.SUBMIT.RETRO.AMB.CONFIRM.EN_US"),
	 GME_SUBMIT_RETRO_AMB_CONFIRM_ES_US("GME.SUBMIT.RETRO.AMB.CONFIRM.ES_US"),
	 EBILL_CONFR_GME_ES_US("EBILL.CONFR.GME.ES_US"),
	 EBILL_CONFR_GME_EN_US("EBILL.CONFR.GME.EN_US"),
	 GME_ACCOUNT_REGISTRATION_CONFIRM_EN_US("GME.ACCOUNT.REGISTRATION.CONFIRM.EN_US"),
	 GME_ACCOUNT_REGISTRATION_CONFIRM_ES_US("GME.ACCOUNT.REGISTRATION.CONFIRM.ES_US"),
	 GME_BILL_PAY_CONFIRM_BANK_EN_US_2("GME.BILL.PAY.CONFIRM.BANK.EN_US"),
	 GME_BILL_PAY_CONFIRM_BANK_ES_US_2("GME.BILL.PAY.CONFIRM.BANK.ES_US"), 
	 GME_BILL_PAY_CONFIRM_CC_EN_US_2("GME_BILL_PAY_CONFIRM_CC.EN_US"),
	 GME_BILL_PAY_CONFIRM_CC_ES_US_2("GME_BILL_PAY_CONFIRM_CC.ES_US"),
	 GME_PAYMTXTN_EMAIL_EN_US("GME.PAYMTXTN.EMAIL.EN_US"),
	 GME_PAYMTXTN_EMAIL_ES_US("GME.PAYMTXTN.EMAIL.ES_US"),
	 DP_PAYMTXTN_EMAIL_EN_US("DP.PAYMTXTN.EMAIL.EN_US"),
	 DP_PAYMTXTN_EMAIL_ES_US("DP.PAYMTXTN.EMAIL.ES_US");
	 

	
	  
	 
	public String templateName;

	EmailTemplateEnum(String templateName) {
		this.templateName = templateName;
	}

	public String getTemplateName() {
		return templateName;
	}

	public static Map<String, Object> getEnumMap() {
		Map<String, Object> enumValMap = new HashMap<>();
		for (EmailTemplateEnum template : EmailTemplateEnum.values()) {
			enumValMap.put(template.getTemplateName(), template);
		}
		return enumValMap;
	}

}
